### ISSUE TITLE
wcs:DescribeCoverage_Response_InterpolationMethods test is still faulty

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#35]
The wcs:DescribeCoverage_Response_InterpolationMethods test seems to sometimes leave out the comma between identifiers in its DescribeCoverage request.

This happens, for example, when testing "https://onestop.cubewerx.com/cubewerx/cubeserv/cite_wcs?DATASTORE=Foundation&service=WCS&request=GetCapabilities&VERSION=1.1.1", which has three coverages: "etopo2", "gtopo30" and "X1km177240497702008GROUPEALTA". The server gets sent the following request:

https://onestop.cubewerx.com/cubewerx/cubeserv/cite_wcs?DATASTORE=Foundation&&service=WCS&request=DescribeCoverage&version=1.1.1&identifiers=etopo2X1km177240497702008GROUPEALTA,gtopo30

which causes an exception report rightly stating that coverage "etopo2X1km177240497702008GROUPEALTA" doesn't exist.

This is also the case for the wcs:DescribeCoverage_Response_Identifier_XML, wcs:DescribeCoverage_Response_SupportedFormat and wcs:DescribeCoverage_Response_FieldIdentifier_XML tests.

**Comment by dstenger** [comment]
Thank you for reporting this issue. We will investigate soon.

**Comment by dstenger** [comment]
Related to #29.

**Comment by lgoltz** [comment]
The problem affects (all) tests of the test group `wcs:DescribeCoverage-main`. The first part of the identifier (before the comma, named `idenfier1`) is selected from the capabilities ($result1) with the  following XPath:

```
$result1/
  *[local-name()='Capabilities']/
  *[local-name()='Contents']//
  *[local-name()='CoverageSummary'][child::*[local-name()='Identifier']][1]/
  *[local-name()='Identifier']/text()
``` 

This selects all first identifiers (`etopo2X1km177240497702008GROUPEALTA`).

The XPath selecting `identifier1` (as well as `identifier2` and `identifier3`) must be fixed to select exactly one identifier.

**Comment by keshav-nangare** [comment]
RI[1]: https://onestop.cubewerx.com/cubewerx/cubeserv/cite_wcs?DATASTORE=Foundation&service=WCS&request=GetCapabilities&VERSION=1.1.1

Question: Is this service consistent with the **`<CoverageSummary>`**?

If we see the response of above RI[1] we found the different level of <CoverageSummary> element.

```
<CoverageSummary>
	<CoverageSummary> 
		<CoverageSummary> 
			<Identifier>etopo2</Identifier>  ===> Identifier1
		</CoverageSummary>
		<CoverageSummary> 
			<Identifier>gtopo30</Identifier>  ====>Identifier2
		</CoverageSummary>
	</CoverageSummary>
	<CoverageSummary> 
		<Identifier>X1km177240497702008GROUPEALTA</Identifier> ====>Identifier1
	</CoverageSummary>
</CoverageSummary>
```

If we see the above the XML snippet to extract identifiers, but the identifire1, identifire2 and identifire3 are at different level. 

If the XPath is correct then the service should be updated with the same level of the <CoverageSummary> element.

If the service is correct then we need to update the XPath accordingly.

@lgoltz  Please provide your thought on this.

**Comment by keshav-nangare** [comment]
Fixed this issue with commit: 2d41cf3b0817ba7c743b975557a5fd96d3e948b4. [PR: #37]

**Comment by pomakis** [comment]
It has not been fixed.  The issue still reproducibly exists as described in my original description of the issue.  I don't seem to have the power to re-open the issue, so I opened a new one (#51).
